site_name: Single cell transcriptomics
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1:
      - General introduction: day1/general_introduction.md
      - Setup: day1/setup.md
      - Introduction scRNAseq: day1/introduction_scrnaseq.md
      - Analysis tools and QC: day1/analysis_tools_qc.md
      - Normalization and scaling: day1/normalization_scaling.md
    - Day 2:
      - Dimensionality reduction: day2/dimensionality_reduction.md
      - Integration: day2/integration.md
      - Clustering: day2/clustering.md
      - Cell annotation: day2/cell_annotation.md
    - Day 3:
      - Differential gene expression: day3/differential_gene_expression.md
      - Enrichment analysis: day3/enrichment_analysis.md
      - Advanced analyses: day3/advanced_analyses.md
      - Trajectory analysis (extra): day3/trajectory_analysis.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg

# Repository
repo_name: sib-swiss/single-cell-training
repo_url: https://github.com/sib-swiss/single-cell-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
