name: Auto extract R code

on:
  push:
  pull_request:

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2.3.2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install codedown
        run: npm install -g codedown
      - name: Modifiy the specific files using scripts
        run: |
          bash ./scripts/extract_code.sh
      - name: Modifiy the specific files using action
        uses: action-owner/action-repo@ref
      - name: Commit and push changes
        run: |
          git config --global user.name "geertvangeest"
          git config --global user.email "geert.vangeest@gmail.com"

          git add -A
          git commit -m "auto-update extracted code"
          git push
