name: Render and publish

on:
    workflow_dispatch:
    push:
      branches:
        - master

jobs:
  docker:
    runs-on: ubuntu-latest
    container: geertvangeest/single-cell-rstudio:latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish to GitHub Pages (and render) 
        run: |
            quarto publish gh-pages . --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
