name: Render and publish

on:
    workflow_dispatch:
    push:
      branches:
        - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  publish-site:
    runs-on: ubuntu-latest
    container:
      image: geertvangeest/single-cell-rstudio:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        run: |
          quarto render
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/master'
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./_site

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     container: geertvangeest/single-cell-rstudio:latest
#     permissions:
#         contents: write
#     steps:
#       - uses: actions/checkout@v4
#       - name: Publish to GitHub Pages (and render) 
#         run: |
#             quarto publish gh-pages . --no-browser
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
